# Copyright (C) 2007 Robotics at Maryland
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  packages/carnetix/SConscript

# Copy Our Build Environment
Import('env')
envl = env.Clone()

# Build the ctx and consolemon
envl.RAMProgram(target = 'MagInclination', 
		source = 'src/MagInclination.cpp',
                int_deps = ['imu','math'])

envl.RAMProgram(target = 'MagInclinationTest', 
		source = 'src/MagInclinationTest.cpp',
                int_deps = ['vehicle','math'])
