# Copyright (C) 2007 Robotics at Maryland
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  packages/carnetix/SConscript

# Build system imports
import helpers

# Copy Our Build Environment
Import('env')
envl = env.Clone()

# Build the ctx and consolemon
helpers.Program(envl, target = 'MagInclination', 
		source = 'src/MagInclination.cpp',
                int_deps = ['imu','math'])
