import os

import distutils.sysconfig

env = Environment()
env.Append(CPPPATH = [ 'include'])

sources = ['src/Vehicle.cpp', 'src/PSU.cpp']
vehicle_lib = env.SharedLibrary(target = 'vehicle', source = sources)


