function convertedControllerState = CppControllerState(ControllerState, too_from)

% We are converting from Matlab to CPP format
if too_from == 1
    i = ControllerState.inertiaEstimate;
    ad = ControllerState.adaptationGain;
    ag = ControllerState.angularGain;

    % Convert static array to individual numbers (HACK!)
    convertedControllerState = struct( ...
    'i0', i(1), 'i1', i(2), 'i2', i(3), ...
    'i3', i(4),  'i4', i(5), 'i5', i(6),...
    'ad0', ad(1), 'ad1', ad(2), 'ad2', ad(3),...
    'ad3', ad(4), 'ad4', ad(5), 'ad5', ad(6),... 
    'ad6', ad(7), 'ad7', ad(8), 'ad8', ad(9),...
    'ag0', ag(1), 'ag1', ag(2), 'ag2', ag(3),...
    'ag3', ag(4), 'ag4', ag(5), 'ag5', ag(6),... 
    'ag6', ag(7), 'ag7', ag(8), 'ag8', ag(9),...
    'depthPGain', ControllerState.depthPGain, ...
    'speedPGain', ControllerState.speedPGain);
    
else
    % Converting from CPP to Matlab
    convertedControllerState = struct('inertiaEstimate', ...
    [ControllerState.i0, ControllerState.i1, ControllerState.i2, ...
    ControllerState.i3,  ControllerState.i4, ControllerState.i5]',...
    'adaptationGain', [ControllerState.ad0, ControllerState.ad1, ControllerState.ad2,...
                      ControllerState.ad3, ControllerState.ad4, ControllerState.ad5,... 
                      ControllerState.ad6, ControllerState.ad7, ControllerState.ad8]',...
    'angularGain', [ControllerState.ag0, ControllerState.ag1, ControllerState.ag2,...
                      ControllerState.ag3, ControllerState.ag4, ControllerState.ag5,... 
                      ControllerState.ag6, ControllerState.ag7, ControllerState.ag8]',...
    'depthPGain', ControllerState.depthPGain, ...
    'speedPGain', ControllerState.speedPGain);
end