AUV_PACKAGES='/home/levashom/auv/trunk/packages';
INCLUDES=['.','sonarUtils','spectrum','dataset','getDirection','pingDetect','sonarPing','time_diff','sonar_quadfit','fft_sonar',AUV_PACKAGES];

#Build common files
osUtils=Object('sonarUtils/sonarUtils.cpp', CPPPATH=INCLUDES);

oDataset=Object('dataset/dataset.cpp', CPPPATH=INCLUDES);
oSpartan=Object('dataset/spartan.cpp', CPPPATH=INCLUDES);
opDetect=Object('pingDetect/pingDetect.cpp', CPPPATH=INCLUDES);
ogetPChunk=Object('getPingChunk/getPingChunk.cpp', CPPPATH=INCLUDES);
#Build the program for testing ping detection
Program('pingDetect/pingDtest',['pingDetect/pingDtest.cpp', osUtils, oDataset, oSpartan, opDetect], CPPPATH=INCLUDES);

oFftSonar=Object('fft_sonar/fft_sonar.cpp',CPPPATH=INCLUDES, LIBS=['gsl','blas']);
oQuadFit=Object('sonar_quadfit/sonar_quadfit.cpp',CPPPATH=INCLUDES, LIBS=['gsl','blas']);
oTimeDiff=Object('time_diff/time_diff.cpp',CPPPATH=INCLUDES, LIBS=['gsl','blas']);
#Build the program to test the quadrature fits
Program('sonar_quadfit/quadfit_test',['sonar_quadfit/quadfit_test.cpp',oFftSonar,oQuadFit], CPPPATH=INCLUDES, LIBS=['gsl','blas']);
#Build program to test the time difference
Program('time_diff/timediff_test',['time_diff/timediff_test.cpp',oTimeDiff,oQuadFit,oFftSonar],CPPPATH=INCLUDES, LIBS=['gsl','blas']);



