function convertedControllerState = CppControllerState(ControllerState, to_from)

% We are converting from Matlab to CPP format
if to_from == 1
    ie = ControllerState.inertiaEstimate;

    % Convert static array to individual numbers (HACK!)
    convertedControllerState = struct( ...
    'angularPGain', ControllerState.angularPGain, ...
    'angularDGain', ControllerState.angularDGain, ...
    'ie0', ie(1), 'ie1', ie(2), 'ie2', ie(3),...
    'ie3', ie(4), 'ie4', ie(5), 'ie5', ie(6),... 
    'ie6', ie(7), 'ie7', ie(8), 'ie8', ie(9),...
    'depthPGain', ControllerState.depthPGain, ...
    'speedPGain', ControllerState.speedPGain);
    
else
    % Converting from CPP to Matlab
    convertedControllerState = struct(...
    'angularPGain', ControllerState.angularPGain, ...
    'angularDGain', ControllerState.angularDGain, ...
    'inertiaEstimate', [ControllerState.ie0, ControllerState.ie1, ControllerState.ie2,...
                      ControllerState.ie3, ControllerState.ie4, ControllerState.ie5,... 
                      ControllerState.ie6, ControllerState.ie7, ControllerState.ie8]',...
    'depthPGain', ControllerState.depthPGain, ...
    'speedPGain', ControllerState.speedPGain);
end