# Copyright (C) 2007 Robotics at Maryland
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  packages/tools/FindBias/SConscript

# Build system imports
import helpers

# Copy Our Build Environment
Import('env')
envl = env.Clone()

# Build the ctx and consolemon
helpers.Program(envl, target = 'BiasFinder', 
		source = 'src/FindBias.cpp',
                int_deps = ['vehicle','math'])