import os

EnsureSConsVersion(0, 96, 93)

env = Environment(ENV=os.environ)

env.MergeFlags(['!pkg-config opencv --libs --cflags'])
env.Append(CCFLAGS = ['-g'])
env.Append(LIBFLAGS = ['-g'])

env.Program('main.cpp')
