Import('env')

env = env.Clone()

if env['DISTNAME'] is 'native':
    env.Append(CPPPATH = ['/opt/local/include'])
    env.Append(LIBPATH = ['/opt/local/lib'])
    env.Append(LIBS    = ['fftw3'])
elif env['DISTNAME'] is 'bfin':
    env.Append(LIBS = ['m', 'bfdsp'])
    
    # Hack to get missing functions (we copied them from uClinux's SVN)
    fr16patch = env.Library('fr16patch', ['cos_fr16.asm', 'sin_fr16.asm'])
    env.Append(LIBS = [fr16patch])

livecat = env.Program('livecat.c')
bffft = env.Program('bffft.cpp')
sonaragent = env.Program('sonaragent.cpp')

env.Install(env['INSTALLPATH'], [bffft, livecat, sonaragent])
