Import('env')

env = env.Clone()

if env['DISTNAME'] is 'native':
    env.Append(CPPPATH = ['/home/jlisee/opt/local/include'])
    env.Append(LIBPATH = ['/home/jlisee/opt/local/lib'])
    env.Append(LIBS    = ['fftw3'])
elif env['DISTNAME'] is 'bfin':
    env.Append(LIBS = ['m', 'bfdsp'])
    
    # Hack to get missing functions (we copied them from uClinux's SVN)
    fr16patch = env.Library('fr16patch', ['cos_fr16.asm', 'sin_fr16.asm'])
    env.Append(LIBS = [fr16patch])



bffft = env.Program('bffft.cpp')
sonaragent = env.Program('sonaragent.cpp')
rtrt = env.Program('rtrt.cpp')
progs = [bffft, sonaragent, rtrt]

if env['DISTNAME'] is 'bfin':
    livecat = env.Program('livecat.c')
    progs += [livecat]

env.Install(env['INSTALLPATH'], progs)
