# Copyright (C) 2007 Maryland Robotics Club
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  wrappers/core/SConscript

import os

# Build System imports
import buildfiles.libs as libs

Import('env')
envl = env.Clone()

# Find all cpp files in the source directory
extra_sources = envl.Glob('src', '*.cpp')
extra_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'wrappers', 'logging')
envl.Append(CPPPATH = os.path.abspath(os.environ['RAM_SVN_DIR']))

# Link to libram_logging.so library
libs.add_internal(envl, 'logging')

# Must link to any features included (for the events)
depends_on = ['math', 'vision', 'vehicle', 'control']
depends_on = filter(lambda f: f in env['features'], depends_on)

for feature_name in depends_on:
    libs.add_internal(envl, feature_name)

# Pattern library directories
base_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'packages', 'logging')
header_dir = os.path.join(base_dir, 'include')

# Need for because Py++ has so odd include paths
envl.Append(CPPPATH = base_dir)

# Headers we are currently wrapping
wrapped_headers = ['EventPlayer.h']
wrapped_headers = [os.path.join(header_dir, h) for h in wrapped_headers]

# Tests
envt = env.Clone()
envt.Append(CPPPATH = os.path.abspath(os.environ['RAM_SVN_DIR']))

test, runner = envt.Tests(int_deps = ['logging'] + depends_on,
                          ext_deps = 'Boost.Python', run = False)

                          
py_sources = [os.path.abspath(s) for s in envl.Glob('python', '*.py')]
def extras(env, output, message = None, deps = None):
    tester = runner(env, output, message, deps)
    py_install = env.Install(dir = os.environ['RAM_SVN_DIR'] + '/build_ext/ext',
                             source = py_sources)

    env.Depends(tester, py_install)    
    return tester
                          
envl.Pypp('_logging', wrapped_headers, module = 'gen_logging.py',
          tester = extras,
          dep_wrappers = ['_core', 'core.py'],
          dont_build = ['SubsystemList.pypp.cpp'],
          extra_sources = [os.path.join(extra_dir, s) for s in extra_sources])
