# Copyright (C) 2007 Robotics at Maryland
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  packages/vision/SConscript

# Build system imports
import libs
import helpers

# Copy Our Build Environment
Import('env')
envl = env.Clone()

# Sources
sources = ['CalibrationTools.cpp']

#A simple calibration tool
helpers.Program(envl, target='CalibrationTool', 
		source = 'CalibrationTools.cpp',
                int_deps = 'vision')
