# Copyright (C) 2007 Maryland Robotics Club
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  wrappers/pattern/SConscript

import os

# Build System imports
import buildfiles.wrap as wrap
import buildfiles.libs as libs
import buildfiles.helpers as helpers

Import('env')
envl = env.Clone()

# Link to libram_pattern.so library
libs.add_internal(envl, 'control')

# Pattern library directories
base_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'packages', 'control')
header_dir = os.path.join(base_dir, 'include')

# Need for because Py++ has so odd include paths
envl.Append(CPPPATH = base_dir)

# Headers we are currently wrapping
wrapped_headers = ['IController.h']
wrapped_headers = [os.path.join(header_dir, h) for h in wrapped_headers]

# Tests
envt = env.Clone()
test_prog, runner = envt.Tests(int_deps = 'control', ext_deps = 'Boost.Python',
                       run = False)

# Wrapper
envl.Pypp('control', wrapped_headers, module = 'gen_control.py',
          tester = runner, dep_wrappers = ['core','math','vehicle'])
