import os

env = Environment(ENV = {'PATH': os.environ['PATH']})
env.Append(CPPPATH = ['/opt/ram/local/include', '/opt/local/include/octave-3.0.0', '/opt/local/include', '#include'])
env.Append(LIBPATH = ['/opt/ram/local/lib', '/opt/local/lib/octave-3.0.0', '/opt/local/lib'])
#env.Append(CPPFLAGS = ['-O3'])

Export('env')
libram_sonar = env.SConscript('src/common.SConscript', variant_dir='#build', duplicate=0)

env = env.Clone()
env.Append(LIBS = [libram_sonar, 'octave'])
Export('env')



tests = env.SConscript('test/SConscript', variant_dir='#build/test', duplicate=0)
#testExec = env.Program('build/test', testFiles)
