# Buildsystem Imports
import libs

Import('env')
envl = env.Clone()

libs.add_external(envl, 'OpenCV')

envl.SharedLibrary(target = 'foo', source = "foo.c")
envl.SharedLibrary(target = 'matt', source = "matt.c")