# Copyright (C) 2007 Robotics at Maryland
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  packages/tools/vision_viewer/SConscript

import os

Import('env')
envl = env.Clone()

# Find all cpp files in the source directory
sources = envl.Glob('src', '*.cpp')

# Add wxWidgets and OpenCV
envl.Append(CPPPATH = 'include')

if 'posix' == os.name:
    envl.AppendUnique(CCFLAGS = ['-fno-strict-aliasing'])

envl.RAMProgram(target = 'Viewer', source = sources,
               int_deps = ['vision'], ext_deps = ['wxWidgets'])

