
env = Environment()

# Add wxWidgets and OpenCV
env.MergeFlags(['!wx-config --cxxflags --libs',
                '!pkg-config opencv --cflags --libs'])

# Program Specific Settings
env.Append(CPPPATH = 'include')
env.Append(CXXFLAGS = '-g')

env.Program(target = 'Viewer',
            source = ['src/viewer.cpp', 'src/CameraView.cpp'])
