import os

# Import path from environment
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env.Append(CPPPATH = ['/opt/IceE-1.3.0/include'])
env.Append(LIBPATH = ['/opt/IceE-1.3.0/lib'])
env.Append(LIBS = ['IceE'])
env.BuildDir('build','src')

env.Append(CPPPATH = ['#/build/ice'])

# NATIVE MARSHALING CODE FOR C++
##############################

env.Command(['build/ice/scope.cpp','build/ice/scope.h'], 
	'../BlackfinScope/scope.ice', '/opt/IceE-1.3.0/bin/slice2cppe --output-dir build/ice $SOURCES')


# EMBEDDED SERVER FOR OSCILLOSCOPE
##############################
env.Program(target = 'build/scoped', source = ['build/main.cpp', 'build/ice/scope.cpp'])
