#! /bin/bash

# This sets up the environment for use of our software
# The only thing you need to do is set the environment variable MRBC_SVN_ROOT
# to the location of the source tree. Then in your shell type 'source setenv'
# and you will be all set. (Note the only works for the current shell)

# Set up PYTHONPATH so imports will work properly
#export PYTHONPATH=$MRBC_SVN_ROOT/deps/cfgparse:$PYTHONPATH    # For nose

# Setup the PATH
export PATH=$MRBC_SVN_ROOT/scripts:$PATH
export LD_LIBRARY_PATH=$MRBC_SVN_ROOT/local/lib:$LD_LIBRARY_PATH

# Setup path for pkgconfig (so it can find our local libraries)
export PKG_CONFIG_PATH=$MRBC_SVN_ROOT/deps/local/lib/pkgconfig:$PKG_CONFIG_PATH

# So configure can find our non-stanard library locations
export LDFLAGS="-L$MRBC_SVN_ROOT/deps/local/lib $LDFLAGS"
export CPPFLAGS="-I$MRBC_SVN_ROOT/deps/local/include $CPPFLAGS"
