# Copyright (C) 2007 Maryland Robotics Club
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  wrappers/pattern/SConscript

import os

# Build System imports
import wrap
import libs

Import('env')
envl = env.Clone()

# Link to libram_pattern.so library
libs.add_internal(envl, 'vision')

# Pattern library directories
base_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'packages', 'vision')
header_dir = os.path.join(base_dir, 'include')

# Need for because Py++ has so odd include paths
envl.Append(CPPPATH = base_dir)

# Headers we are currently wrapping
wrapped_headers = ['Camera.h',
                   'OpenCVCamera.h',
                   'GateDetector.h',
                   'BinDetector.h',
                   'RedLightDetector.h',
                   'OrangePipeDetector.h']
wrapped_headers = [os.path.join(header_dir, h) for h in wrapped_headers]

print 'HEADERS:',wrapped_headers
wrap.wrap_headers(envl, 'vision',
                  wrapped_headers,
		  gen_mod = 'gen_vision')
