Import('env')

env.Append(LIBS = ['fftw3', 'UnitTest++'])
src = Split("""
	src/Test.cpp
	src/TestSampleDelay.cpp
	src/TestDFTs.cpp
	src/TestTDOAxcorr.cpp
	""")

tests = env.Program('Tests_sonar', src)
Return('tests')
