# Copyright (C) 2007 Maryland Robotics Club
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  wrappers/pattern/SConscript

import os

# Build System imports
import buildfiles.wrap as wrap
import buildfiles.libs as libs
import buildfiles.helpers as helpers

Import('env')
envl = env.Clone()

# Link to libram_pattern.so library
libs.add_internal(envl, 'math')

# Pattern library directories
base_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'packages', 'math')
header_dir = os.path.join(base_dir, 'include')

# Need for because Py++ has so odd include paths
envl.Append(CPPPATH = base_dir)

# Headers we are currently wrapping
#wrapped_headers = ['Vector3.h','Vector4.h', 'Matrix3.h', 'Matrix4.h',
#                   'Quaternion.h']
wrapped_headers = ['Math.h', 'Vector3.h', 'Quaternion.h', 'Matrix3.h']
wrapped_headers = [os.path.join(header_dir, h) for h in wrapped_headers]

# Tests
envt = env.Clone()
test_prog, runner = envt.Tests(int_deps = 'math', ext_deps = 'Boost.Python',
                               run = False)

# Wrappers
libs.add_external(envl, 'Boost.Python')
envl.Pypp('math', wrapped_headers,
          module = 'gen_math.py',
          tester = runner)
