# Copyright (C) 2007 Maryland Robotics Club
# Copyright (C) 2007 Joseph Lisee <jlisee@umd.edu>
# All rights reserved.
#
# Author: Joseph Lisee <jlisee@umd.edu>
# File:  wrappers/pattern/SConscript

import os

# Build System imports
import buildfiles.libs as libs

Import('env')
envl = env.Clone()

# Find all cpp files in the source directory
extra_sources = envl.Glob('src', '*.cpp')

# Link to libram_pattern.so library
libs.add_external(envl, 'Boost.Python')

# Pattern library directories
base_dir = os.path.join(os.environ['RAM_SVN_DIR'], 'wrappers', 'samples')
header_dir = os.path.join(base_dir, 'include')

# Need for because Py++ has so odd include paths
envl.Append(CPPPATH = base_dir)
# Headers we are currently wrapping
wrapped_headers = ['SharedPtrVector.h', 'CodeInject.h']
wrapped_headers = [os.path.join(header_dir, h) for h in wrapped_headers]

# Tests
envt = env.Clone()
test, runner = envt.Tests(ext_deps = 'Boost.Python', run = False)

envl.Pypp('samples', [os.path.join(header_dir, h) for h in wrapped_headers],
          module = 'gen_samples.py',
          extra_sources = [os.path.join(base_dir, s) for s in extra_sources],
          tester = runner)
