# Exported from MPLAB IDE project `dsPIC30F4012_servo.mcp' on Thu Apr 17 22:03:44 2008.

"dsPIC30F4012_servo.hex" : "dsPIC30F4012_servo.cof"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-bin2hex.exe" "dsPIC30F4012_servo.cof"

"dsPIC30F4012_servo.cof" : "ADC.o" "main.o" "iir.o" "uart.o"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=30F4012 "ADC.o" "main.o" "iir.o" "uart.o" -o"dsPIC30F4012_servo.cof" -Wl,--script="C:\Program Files\Microchip\MPLAB C30\support\gld\p30f4012.gld",-Map="dsPIC30F4012_servo.map",--report-mem

"ADC.o" : "ADC.c" "C:\PICprog\dsPIC30F4012_servo_ENEE461\scottcommon.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30f4012.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30fxxxx.h" "C:\PICprog\dsPIC30F4012_servo_ENEE461\ADC.c"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=30F4012 -x c -c   "ADC.c" -o"ADC.o" -g -Wall

"main.o" : "main.c" "C:\PICprog\dsPIC30F4012_servo_ENEE461\scottcommon.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30f4012.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30fxxxx.h" "C:\PICprog\dsPIC30F4012_servo_ENEE461\main.c"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=30F4012 -x c -c   "main.c" -o"main.o" -g -Wall

"iir.o" : "iir.c" "C:\PICprog\dsPIC30F4012_servo_ENEE461\iir.c"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=30F4012 -x c -c   "iir.c" -o"iir.o" -g -Wall

"uart.o" : "uart.c" "C:\PICprog\dsPIC30F4012_servo_ENEE461\scottcommon.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30f4012.h" "c:\program files\microchip\mplab c30\bin\..\support\h\p30fxxxx.h" "C:\PICprog\dsPIC30F4012_servo_ENEE461\uart.c"
	"C:\Program Files\Microchip\MPLAB C30\bin\pic30-gcc.exe" -mcpu=30F4012 -x c -c   "uart.c" -o"uart.o" -g -Wall

clean : 
	del "ADC.o" "main.o" "iir.o" "uart.o" "dsPIC30F4012_servo.cof" "dsPIC30F4012_servo.hex"

