env = Environment(tools = ['default', 'Microchip'],
                  toolpath = ['.'],
				  MCPU = '30f4011')

env.Append(CPPPATH = ['../../sonar/sonarController/include'])
sourcefiles = ['../../sonar/sonarController/src/dft.c','leoadc.c']
env.Hex('out.hex', env.Program(sourcefiles))
